### ISSUE TITLE
Parrallelize transaction download

### ISSUE THREAD

**Issue by awishformore** [alvalor/alvalor-go#105]
Currently, we simply request all unknown transactions from the peer who has informed us about them. Instead, we should have some kind of pending queue for transaction downloads and evenly dispatch the request amongst peers we know have them.

**Comment by awishformore** [comment]
This is especially important if the amount of transactions in the memory pool is big. Otherwise, we might fail to send all requested transactions due to the sending buffer filling up. We should request a low number of transactions per peer at a time.

**Comment by sshumakov** [comment]
@awishformore, are you working on this? From issues that your referenced and closed I understand that the missing part is pending queue for transaction downloads.

**Comment by awishformore** [comment]
No, the missing parts are:
1) Downloading the block headers.
2) Downloading the block transaction lists.
3) Downloading the transactions.
I'm not sure how much sense it makes to start on this without having the other two.

**Comment by sshumakov** [comment]
#150

**Comment by awishformore** [comment]
This is mostly done in #151 now.
