### ISSUE TITLE
Remove hasher package

### ISSUE THREAD

**Issue by awishformore** [alvalor/alvalor-go#66]
In general, we should only abstract something if it's useful for other people (hasher isn't) or if it would be a big change to make modifications (changing the hash function isn't). So I think I think I went a bit overboard with this one and it's fine to just directly use the hash function.

**Comment by sshumakov** [comment]
Agree, unless we need to test something where we would like to isolate real dependency (e.g. tpc connection) :)

**Comment by awishformore** [comment]
There is already an interface for that (`net.Conn`), no need to use a TPC connection.

**Comment by awishformore** [comment]
Looking at it again, it actually is OK to leave it as is. Since the standard hash function will return a byte array, but we want to work mostly with byte slices. It will also make it easier if we decide to use our own type definition for hashes.
